In [85]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [92]:
df=pd.read_csv("/kaggle/input/tennis/tennis.csv")
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [70]:
df.isna().sum()

outlook     0
temp        0
humidity    0
windy       0
play        0
dtype: int64

In [71]:
inputs=df.drop('play',axis=1)
target=df["play"]

In [72]:
inputs

     outlook  temp humidity  windy
0      sunny   hot     high  False
1      sunny   hot     high   True
2   overcast   hot     high  False
3      rainy  mild     high  False
4      rainy  cool   normal  False
5      rainy  cool   normal   True
6   overcast  cool   normal   True
7      sunny  mild     high  False
8      sunny  cool   normal  False
9      rainy  mild   normal  False
10     sunny  mild   normal   True
11  overcast  mild     high   True
12  overcast   hot   normal  False
13     rainy  mild     high   True

In [98]:
target

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: play, dtype: object

In [74]:
l=LabelEncoder()

In [75]:
inputs["outlook_n"]=l.fit_transform(df["outlook"])
inputs["temp_n"]=l.fit_transform(df["temp"])
inputs["humidity_n"]=l.fit_transform(df["humidity"])
inputs["windy_n"]=l.fit_transform(df["windy"])

In [79]:
inputs

    outlook_n  temp_n  humidity_n  windy_n
0           2       1           0        0
1           2       1           0        1
2           0       1           0        0
3           1       2           0        0
4           1       0           1        0
5           1       0           1        1
6           0       0           1        1
7           2       2           0        0
8           2       0           1        0
9           1       2           1        0
10          2       2           1        1
11          0       2           0        1
12          0       1           1        0
13          1       2           0        1

In [80]:
classifier=GaussianNB()
classifier.fit(inputs,target)

GaussianNB()

In [81]:
classifier.score(inputs,target)

0.9285714285714286

In [97]:
classifier.predict(np.array([2,1,0,1]).reshape(1,-1))

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"

array(['no'], dtype='<U3')